#FROM mesosphere/mesos-slave-dind:mesos-0.24.0_dind-0.2_docker-1.8.2_ubuntu-14.04.3
FROM sttts/mesos-slave-dind:mesos-0.24.0-1.0.27.ubuntu1404-docker-1.8.2-0-trusty
MAINTAINER James DeFelice <james@mesosphere.io>

RUN apt-get install -y -q aufs-tools
